In [1]:
#
#抓取台灣銀行牌告匯率 by 大數學堂
#http://www.largitdata.com

import pandas as pd
from datetime import datetime
import sqlite3

#source
url="http://rate.bot.com.tw/xrt?Lang=zh-TW"

#讀取網頁
dfs=pd.read_html(url)

#測試
#type(dfs)
#len(dfs)

#資料呈現
#dfs[0]

currency=dfs[0]

In [9]:
#檢查
#type(currency)

#擷取需要的欄位
currency_fix=currency.ix[:,0:5]

#檢查
#currency_fix

#自訂欄位名稱
currency_fix.columns=[u'幣別',u'現金匯率-本行買入',u'現金匯率-本行賣出',u'即期匯率-本行買入',u'即期匯率-本行賣出']

#檢查
#currency_fix

#清除幣別欄重複字元
currency_fix[u'幣別']=currency_fix[u'幣別'].str.extract('\((\w+)\)')

#檢查
currency_fix

#存檔
#currency_fix.to_excel('currency.xlsx')
#currency_fix.to_csv('currency.csv')

/home/smile_hsu/.local/lib/python3.5/site-packages/ipykernel_launcher.py:18: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0   USD    29.555    30.097    29.855    29.955
1   HKD     3.664     3.854     3.779     3.839
2   GBP     39.32     41.25     40.19     40.61
3   AUD     22.16     22.82     22.35     22.58
4   CAD     22.96      23.7     23.23     23.45
5   SGD     21.77     22.55     22.19     22.37
6   CHF     29.22     30.28     29.75     30.04
7   JPY    0.2613    0.2723    0.2677    0.2717
8   ZAR         -         -      2.34      2.42
9   SEK      3.04      3.55      3.38      3.48
10  NZD     20.32     20.95     20.56     20.76
11  THB    0.8272    0.9702    0.9157    0.9557
12  PHP    0.4978    0.6308         -         -
13  IDR   0.00178   0.00248         -         -
14  EUR     34.63     35.78     35.13     35.53
15  KRW   0.02598   0.02988         -         -
16  VND   0.00094   0.00144         -         -
17  MYR      6.44      8.07         -         -
18  CNY     4.604     4.766     4.676     4.726

In [4]:
#將資料存到Sqlite

#新增日期欄位&使用今天的日期
currency_fix['Date']=datetime.now().strftime('%Y-%m-%d')
#檢查格式
currency_fix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
幣別           19 non-null object
現金匯率-本行買入    19 non-null object
現金匯率-本行賣出    19 non-null object
即期匯率-本行買入    19 non-null object
即期匯率-本行賣出    19 non-null object
Date         19 non-null object
dtypes: object(6)
memory usage: 992.0+ bytes

In [5]:
#將Data欄位用pandas轉成日期的資料型態
currency_fix['Date']=pd.to_datetime(currency_fix['Date'])

In [6]:
#檢查格式
currency_fix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
幣別           19 non-null object
現金匯率-本行買入    19 non-null object
現金匯率-本行賣出    19 non-null object
即期匯率-本行買入    19 non-null object
即期匯率-本行賣出    19 non-null object
Date         19 non-null datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 992.0+ bytes

In [7]:
#印出&檢查內容
currency_fix

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出       Date
0   USD    29.555    30.097    29.855    29.955 2018-05-20
1   HKD     3.664     3.854     3.779     3.839 2018-05-20
2   GBP     39.32     41.25     40.19     40.61 2018-05-20
3   AUD     22.16     22.82     22.35     22.58 2018-05-20
4   CAD     22.96      23.7     23.23     23.45 2018-05-20
5   SGD     21.77     22.55     22.19     22.37 2018-05-20
6   CHF     29.22     30.28     29.75     30.04 2018-05-20
7   JPY    0.2613    0.2723    0.2677    0.2717 2018-05-20
8   ZAR         -         -      2.34      2.42 2018-05-20
9   SEK      3.04      3.55      3.38      3.48 2018-05-20
10  NZD     20.32     20.95     20.56     20.76 2018-05-20
11  THB    0.8272    0.9702    0.9157    0.9557 2018-05-20
12  PHP    0.4978    0.6308         -         - 2018-05-20
13  IDR   0.00178   0.00248         -         - 2018-05-20
14  EUR     34.63     35.78     35.13     35.53 2018-05-20
15  KRW   0.02598   0.02988         -         - 2018-05-20
16  VND   0.00094   0.00144         -         - 2018-05-20
17  MYR      6.44      8.07         -         - 2018-05-20
18  CNY     4.604     4.766     4.676     4.726 2018-05-20

In [10]:
#寫檔
with sqlite3.connect('currency.sqlite') as db:
    currency_fix.to_sql('currency',con=db,if_exists='append')

In [11]:
#讀檔(在jupyter上直接看)
with sqlite3.connect('currency.sqlite') as db:
    df=pd.read_sql_query('select * from currency', con=db)
df

    index   幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出
0       0  USD    29.555    30.097    29.855    29.955
1       1  HKD     3.664     3.854     3.779     3.839
2       2  GBP     39.32     41.25     40.19     40.61
3       3  AUD     22.16     22.82     22.35     22.58
4       4  CAD     22.96      23.7     23.23     23.45
5       5  SGD     21.77     22.55     22.19     22.37
6       6  CHF     29.22     30.28     29.75     30.04
7       7  JPY    0.2613    0.2723    0.2677    0.2717
8       8  ZAR         -         -      2.34      2.42
9       9  SEK      3.04      3.55      3.38      3.48
10     10  NZD     20.32     20.95     20.56     20.76
11     11  THB    0.8272    0.9702    0.9157    0.9557
12     12  PHP    0.4978    0.6308         -         -
13     13  IDR   0.00178   0.00248         -         -
14     14  EUR     34.63     35.78     35.13     35.53
15     15  KRW   0.02598   0.02988         -         -
16     16  VND   0.00094   0.00144         -         -
17     17  MYR      6.44      8.07         -         -
18     18  CNY     4.604     4.766     4.676     4.726